apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>K8s Nginx!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Kubernetes NGINX Server!</h1>
    <p> This page is served from a ConfigMap in Kubernetes. If you see this page, 
    the deployment is working fine.</p>

    <p>For online documentation and support please refer to
    <a href="https://cloudspinx.com/">cloudspinx.com</a>.<br/>
    Commercial support is available at
    <a href="https://cloudspinx.com/">cloudspinx.com</a>.</p>

    <p><em>Thank you for using nginx.</em></p>
    </body>
    </html>
